view_layout:
  grid-area: "prod_cons_chart_title"
type: custom:bubble-card
card_type: separator
name: Výroba a spotřeba
icon: mdi:home-lightning-bolt-outline
styles: |
  .bubble-line {
    background: var(--primary-text-color);
    opacity: 0.1;
  }
  .bubble-container {
    color: var(--text-color);
  }